[package]
name = "variables_test"
version = "0.1.0"
edition = "2021"

[[bin]]

name = "variables"
path = "src/types.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
